
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import uts.r6.KoneksiDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author -asus-
 */
public class Menu extends javax.swing.JFrame {

    int [] i = new int[6];
    int [] j = new int[6];
    
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labeltanggal = new javax.swing.JLabel();
        labelkasir = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelkasir1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FC = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        CF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        esteh = new javax.swing.JCheckBox();
        esjer = new javax.swing.JCheckBox();
        esmil = new javax.swing.JCheckBox();
        Teh = new javax.swing.JTextField();
        Jer = new javax.swing.JTextField();
        Mil = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bPrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nomeja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cf = new javax.swing.JCheckBox();
        cc = new javax.swing.JCheckBox();
        fc = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jMakan = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jMinum = new javax.swing.JTextField();
        bTotal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama ", "NoMeja", "Makanan", "Minuman", "SubTotal", "Bayar", "Kembali"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 150, 580, 170);

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));
        jPanel1.setLayout(null);

        labeltanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeltanggal.setForeground(new java.awt.Color(255, 255, 255));
        labeltanggal.setText("Tanggal");
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(970, 40, 120, 15);

        labelkasir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelkasir.setForeground(new java.awt.Color(255, 255, 255));
        labelkasir.setText("Saadatul");
        jPanel1.add(labelkasir);
        labelkasir.setBounds(1060, 10, 70, 15);

        labeljam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setText("Jam");
        jPanel1.add(labeljam);
        labeljam.setBounds(970, 70, 100, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PINK RESTO");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 20, 270, 50);

        labelkasir1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelkasir1.setForeground(new java.awt.Color(255, 255, 255));
        labelkasir1.setText("Nama Kasir : ");
        jPanel1.add(labelkasir1);
        labelkasir1.setBounds(970, 10, 80, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1140, 90);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        FC.setText("0");
        jPanel2.add(FC);
        FC.setBounds(290, 230, 150, 30);

        CC.setText("0");
        jPanel2.add(CC);
        CC.setBounds(290, 200, 150, 30);

        CF.setText("0");
        jPanel2.add(CF);
        CF.setBounds(290, 170, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Minuman");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 320, 70, 15);

        esteh.setText("Es Teh");
        esteh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estehMouseClicked(evt);
            }
        });
        jPanel2.add(esteh);
        esteh.setBounds(20, 340, 90, 23);

        esjer.setText("Es Jeruk");
        esjer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esjerMouseClicked(evt);
            }
        });
        jPanel2.add(esjer);
        esjer.setBounds(20, 370, 100, 23);

        esmil.setText("Es Milo");
        esmil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esmilMouseClicked(evt);
            }
        });
        jPanel2.add(esmil);
        esmil.setBounds(20, 400, 90, 23);

        Teh.setText("0");
        jPanel2.add(Teh);
        Teh.setBounds(290, 330, 150, 30);

        Jer.setText("0");
        jPanel2.add(Jer);
        Jer.setBounds(290, 360, 150, 30);

        Mil.setText("0");
        jPanel2.add(Mil);
        Mil.setBounds(290, 390, 150, 30);
        jPanel2.add(kembali);
        kembali.setBounds(140, 550, 170, 30);
        jPanel2.add(bayar);
        bayar.setBounds(140, 520, 170, 30);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel2.add(total);
        total.setBounds(140, 490, 170, 30);

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel2.add(bSave);
        bSave.setBounds(100, 590, 73, 23);

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel2.add(bClear);
        bClear.setBounds(280, 590, 73, 23);

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(bDelete);
        bDelete.setBounds(370, 590, 73, 23);

        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jPanel2.add(bPrint);
        bPrint.setBounds(460, 590, 73, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pesanan");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 130, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Infrormasi Pemesan");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 10, 160, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nama");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 50, 50, 20);
        jPanel2.add(nama);
        nama.setBounds(90, 40, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("No Meja");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 90, 50, 20);
        jPanel2.add(nomeja);
        nomeja.setBounds(90, 80, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Total");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 490, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Bayar");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 520, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kembali");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 550, 50, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Makanan");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 160, 70, 20);

        cf.setText("Chicken Fire");
        cf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cfMouseClicked(evt);
            }
        });
        cf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfActionPerformed(evt);
            }
        });
        jPanel2.add(cf);
        cf.setBounds(10, 180, 110, 30);

        cc.setText("Chicken Cheese");
        cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ccMouseClicked(evt);
            }
        });
        jPanel2.add(cc);
        cc.setBounds(10, 210, 120, 30);

        fc.setText("Fried Chicken");
        fc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fcMouseClicked(evt);
            }
        });
        jPanel2.add(fc);
        fc.setBounds(10, 240, 110, 30);

        jLabel17.setText("Jumlah");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 280, 50, 14);
        jPanel2.add(jMakan);
        jMakan.setBounds(290, 270, 150, 30);

        jLabel18.setText("Jumlah");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 440, 50, 14);
        jPanel2.add(jMinum);
        jMinum.setBounds(290, 430, 150, 30);

        bTotal.setText("Total");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });
        jPanel2.add(bTotal);
        bTotal.setBounds(20, 590, 57, 23);

        jLabel2.setText("Harga");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 160, 50, 14);

        jLabel3.setText("Rp. 25000");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 250, 60, 14);

        jLabel11.setText("Rp. 35000");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(180, 190, 60, 14);

        jLabel12.setText("Rp. 30000");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(180, 220, 60, 14);

        jLabel13.setText("Harga");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(190, 320, 50, 14);

        jLabel19.setText("Rp. 6000");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(180, 350, 60, 14);

        jLabel20.setText("Rp. 8000");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(180, 380, 60, 14);

        jLabel21.setText("Rp. 12000");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(180, 410, 60, 14);

        jLabel22.setText("Harga");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(190, 160, 29, 14);

        jLabel23.setText("Rp. 35000");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(180, 190, 60, 14);

        jLabel24.setText("Rp. 30000");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(180, 220, 60, 14);

        jLabel25.setText("Rp. 25000");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(180, 250, 60, 14);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(190, 590, 80, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 550, 640);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Detail Pesanan");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(230, 10, 140, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(570, 100, 580, 40);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(-10, 0, 1170, 750);

        setBounds(0, 0, 1176, 788);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        if ("".equals(nama.getText()) || "".equals(nomeja.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi data ", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        } else {
            int makan = Integer.parseInt(String.valueOf(jMakan.getText()));
            int minum = Integer.parseInt(String.valueOf(jMinum.getText()));
            int totalll = makan + minum;
            
            total.setText(String.valueOf(totalll));
        
            
            String SQL = "INSERT INTO tabel_transaksi (nama,no_meja,makanan,minuman,total,bayar,kembali) " 
                    + "VALUES ('"+nama.getText()+"','"+nomeja.getText()+"','"+jMakan.getText()+"','"+jMinum.getText()+"','"+total.getText()+"','"+bayar.getText()
                    +"','"+kembali.getText()+"')";
            int status = KoneksiDB.execute(SQL); 
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
              
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
             
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("PINK RESTO");
        MessageFormat footer  = new MessageFormat("Page {0,number,integer}   ");
        try {
            tabel1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);     
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrintActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        nama.setText(""); 
        nomeja.setText("");
        CF.setText("0");
        CC.setText("0");
        FC.setText("0");
        Teh.setText("0");
        Jer.setText("0");
        Mil.setText("0");
        total.setText("0");
        bayar.setText("0");
        kembali.setText("0");
        jMakan.setText("");
        jMinum.setText("");
        cc.setSelected(false);
        cf.setSelected(false);
        fc.setSelected(false);
        esteh.setSelected(false);
        esjer.setSelected(false);
        esmil.setSelected(false);
    }//GEN-LAST:event_bClearActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
       int baris = tabel1.getSelectedRow();
       if (baris != -1){
           String Nama = tabel1.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM tabel_transaksi WHERE nama='"+Nama+"'";
           int status = KoneksiDB.execute(SQL);
           if (status==1){
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else {
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       } else {
           JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
        // TODO add your handling code here:
        
         int mak = Integer.parseInt(jMakan.getText());
         int mik = Integer.parseInt(jMinum.getText());
        
        int Jumlah = mak + mik;

        int SubTotal = (Jumlah);
        String iSubTotal = String.valueOf(SubTotal);
        total.setText(iSubTotal);
        
        int bay = Integer.parseInt(bayar.getText());
        int tot = Integer.parseInt(total.getText());
        
        int Kembali = bay - tot;
        
        int kembalian = (Kembali);
        String iKembali = String.valueOf(kembalian);
        kembali.setText(iKembali);
    
        if (SubTotal > 200000){
            int diskon = (int) (SubTotal*10/100);
            total.setText(String.valueOf(SubTotal-diskon));
        } else 
            total.setText(String.valueOf(SubTotal));
    }//GEN-LAST:event_bTotalActionPerformed

    private void cfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cfMouseClicked
        // TODO add your handling code here:
        
        int ChickF = Integer.parseInt(CF.getText());
        int icf = 35000;
        
        if(cf.isSelected()) {
            i[0] = (ChickF * icf);
            String pMakanan = String.valueOf(i[0]);
            jMakan.setText(pMakanan);
        }
    }//GEN-LAST:event_cfMouseClicked

    private void ccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccMouseClicked
        // TODO add your handling code here:
        
        int ChickC = Integer.parseInt(CC.getText());
        int icc = 30000;
        
        if(cc.isSelected()) {
            i[1] = (ChickC * icc);
            String pMakanan = String.valueOf(i[1]);
            jMakan.setText(pMakanan);
        }
    }//GEN-LAST:event_ccMouseClicked

    private void fcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcMouseClicked
        // TODO add your handling code here:
        
        int FriedC = Integer.parseInt(FC.getText());
        int ifc = 25000;
        
        if(fc.isSelected()) {
            i[2] = (FriedC * ifc);
            String pMakanan = String.valueOf(i[2]);
            jMakan.setText(pMakanan);
        }
    }//GEN-LAST:event_fcMouseClicked

    private void estehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estehMouseClicked
        // TODO add your handling code here:
        int Est = Integer.parseInt(Teh.getText());
        int iteh = 6000;
        
        if(esteh.isSelected()) {
            i[3] = (Est * iteh);
            String pMinuman = String.valueOf(i[3]);
            jMinum.setText(pMinuman);
        }
    }//GEN-LAST:event_estehMouseClicked

    private void esjerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esjerMouseClicked
        // TODO add your handling code here:
        
        int EsJ = Integer.parseInt(Jer.getText());
        int ijer = 8000;
        
        if(esjer.isSelected()) {
            i[4] = (EsJ * ijer);
            String pMinuman = String.valueOf(i[4]);
            jMinum.setText(pMinuman);
        }
    }//GEN-LAST:event_esjerMouseClicked

    private void esmilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esmilMouseClicked
        // TODO add your handling code here:
        
        int EsM = Integer.parseInt(Mil.getText());
        int imil = 12000;
        
        if(esmil.isSelected()) {
            i[5] = (EsM * imil);
            String pMinuman = String.valueOf(i[5]);
            jMinum.setText(pMinuman);
        }
    }//GEN-LAST:event_esmilMouseClicked

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalActionPerformed

    private void cfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CC;
    private javax.swing.JTextField CF;
    private javax.swing.JTextField FC;
    private javax.swing.JTextField Jer;
    private javax.swing.JTextField Mil;
    private javax.swing.JTextField Teh;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bTotal;
    private javax.swing.JTextField bayar;
    private javax.swing.JCheckBox cc;
    private javax.swing.JCheckBox cf;
    private javax.swing.JCheckBox esjer;
    private javax.swing.JCheckBox esmil;
    private javax.swing.JCheckBox esteh;
    private javax.swing.JCheckBox fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMakan;
    private javax.swing.JTextField jMinum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembali;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labelkasir;
    private javax.swing.JLabel labelkasir1;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomeja;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"Nama","NoMeja","Makanan","Minuman","SubTotal","Bayar","Kembali"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tabel_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String Nama = rs.getString(1);
                String NoMeja = rs.getString(2);
                String Makanan = rs.getString(3);
                String Minuman = rs.getString(4);
                String SubTotal = rs.getString(5);
                String Bayar = rs.getString(6);
                String Kembali = rs.getString(7);
                
                String data[] = {Nama,NoMeja,Makanan,Minuman,SubTotal,Bayar,Kembali};
                dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel1.setModel(dtm);
    }
    
     public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new 
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal.setText(kal.format(skrg));
    }
    
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <=9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                labeljam.setText("Jam "+jam+ ":" + menit +":"+detik);
            }
        };
    new Timer(100, taskPerformer).start();
    
    }
}

